### ISSUE TITLE
能否支持下Remax小程序开发框架

### ISSUE THREAD

**Issue by Emp2612** [iconfont-cli/taro-iconfont-cli#14]
能否支持下Remax小程序开发框架，一套真正的React开发微信小程序的方案，现在组件很少，期待能支持

**Comment by fwh1990** [comment]
你用到生产环境了？我看remaxjs的发版速度有点猛啊！

**Comment by Emp2612** [comment]
> 你用到生产环境了？我看remaxjs的发版速度有点猛啊！

生产环境试过了，还是很不错，准备用上，但是目前UI库还不全，想着尝试一下

**Comment by fwh1990** [comment]
好的。如果remaxjs的api不稳定的话，我不知道现在是否是支持它的最佳时期？然后我粗略看了下，remax目前好像只支持微信和支付宝的小程序。

**Comment by fwh1990** [comment]
基于remax作者这个issue https://github.com/remaxjs/remax/issues/755 ，我觉得还是再等等，2.0出来再处理

**Comment by Emp2612** [comment]
> 基于remax作者这个issue [remaxjs/remax#755](https://github.com/remaxjs/remax/issues/755) ，我觉得还是再等等，2.0出来再处理

感谢大佬，辛苦！

**Comment by fwh1990** [comment]
再试了一次，发现实现很快。今晚开个仓库

**Comment by fwh1990** [comment]
Hello，移步到：[remax-iconfont-cli](https://github.com/iconfont-cli/remax-iconfont-cli)
