### ISSUE TITLE
如何在一个项目中支持多个iconfont?

### ISSUE THREAD

**Issue by summer88123** [iconfont-cli/taro-iconfont-cli#16]
项目中为了区分，添加了多个iconfont项目。使用命令行的时候能指定配置文件么？从源码看似乎硬编码了iconfont.json文件

**Comment by fwh1990** [comment]
之前考虑过同时融合多个iconfont地址，即类似 `{ symbol_url: [ "http://xxxxx", "http://yyyy" ] }` 这种形式。后来感觉是个伪需求，就没上这个功能。

你想要的应该也是这种吧？

**Comment by fwh1990** [comment]
还是说你就是想把这些图标分开到不同的目录？

**Comment by summer88123** [comment]
最终的结果是希望不同的iconfont地址，可以对应不同的入口组件。就是分开放到不同的目录。
我们的需求是不同业务场景使用了不同的iconfont项目，具体的icon name是服务端下发的。
我觉得`npx iconfont-init` 命令支持输出文件名参数，`npx iconfont-taro`命令支持指定配置文件参数，就可以满足需求了

**Comment by fwh1990** [comment]
安装**1.2.0**即可，查看CHANGELOG.md 或者 README.md 可查看相关命令用法
