### ISSUE TITLE
Taro2是否支持，报未发现组件

### ISSUE THREAD

**Issue by xiangzi-jiangxin** [iconfont-cli/taro-iconfont-cli#17]

**Comment by fwh1990** [comment]
明天尝试一下taro2

**Comment by fwh1990** [comment]
Hello，我测试了taro@2.0.7，可以正常运行图标组件。

麻烦你贴出报错信息？以及执行`taro info`导出的信息？

**Comment by xiangzi-jiangxin** [comment]
之前用的Taro@2.1.0版本，刚刚Taro更新到2.1.1版本了，升级Taro后，问题不存在了。
