### ISSUE TITLE
微信编译报错

### ISSUE THREAD

**Issue by mynamezhaoyu** [iconfont-cli/taro-iconfont-cli#18]
jsEnginScriptError
Component is not found in path "components/iconfont/index.weapp" (using by "components/forecast/forecast");onAppRoute
Error: Component is not found in path "components/iconfont/index.weapp" (using by "components/forecast/forecast")

"taro-iconfont-cli": "^1.1.0"

**Comment by fwh1990** [comment]
现在是 `taro-iconfont-cli@1.2.0`，建议升级后看下有没有报错

**Comment by fwh1990** [comment]
顺便提供一下taro的版本

**Comment by mynamezhaoyu** [comment]
taro-cli 的问题，我降级了就可以了。阿西吧。真的恶心

**Comment by fwh1990** [comment]
好像2.1.0有问题，有其它小伙伴出现过，升级到2.1.x可以解决。另外建议升级到最新版 taro-iconfont-cli
