### ISSUE TITLE
taro编译成qq小程序时，qss编译报错

### ISSUE THREAD

**Issue by Alubb77** [iconfont-cli/taro-iconfont-cli#19]
报错信息：
./src/components/iconfont/qq/qq.qss 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .icon {
|   background-repeat: no-repeat;
| }

**Comment by Alubb77** [comment]
taro版本：2.1.4
taro-iconfont-cli 版本：2.0.0
微信一切正常，qq编译报错

**Comment by Alubb77** [comment]
依赖更新到最新版就好了

**Comment by fwh1990** [comment]
> 依赖更新到最新版就好了

是指哪边的依赖？

**Comment by Alubb77** [comment]
taro和taro-iconfont-cli都升级到最新版就好了
