### ISSUE TITLE
【需求】希望能对uni-app也支持一下

### ISSUE THREAD

**Issue by Emp2612** [iconfont-cli/taro-iconfont-cli#22]
uni-app的图标引入方法无法使用彩色，且引入方法不统一，使用起来很不方便。希望作者看下，对uin-app看能否也支持一下

**Comment by fwh1990** [comment]
有这个计划。老早就创建了 项目：https://github.com/iconfont-cli/uni-app-iconfont-cli 

最近在开发ts node框架，得规划一下时间

**Comment by Emp2612** [comment]
膜拜下大佬
