### ISSUE TITLE
文档需要更新

### ISSUE THREAD

**Issue by GreatAuk** [iconfont-cli/taro-iconfont-cli#33]
![image](https://user-images.githubusercontent.com/20253809/90117243-381e7680-dd89-11ea-8e8f-44eee3717c4f.png)

**Comment by fwh1990** [comment]
Hello，这个已经处理了，参考另一个分支： https://github.com/iconfont-cli/taro-iconfont-cli/tree/taro-3.0.8 
由于Taro3.0.8还未发布，所以需要再等一等才能合并进去。感谢关注

**Comment by fwh1990** [comment]
#28
