### ISSUE TITLE
现在安装会报送这样的错误，卸载掉mini-program-iconfont-cli后再install taro-iconfont-cli就会有这样的问题

### ISSUE THREAD

**Issue by D1N910** [iconfont-cli/taro-iconfont-cli#4]
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /private/var/root/node_modules/taro-iconfont-cli/node_modules/mini-program-iconfont-cli/commands;createQqIcon.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/private/var/root/node_modules/taro-iconfont-cli/node_modules/mini-program-iconfont-cli/commands;createQqIcon.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2019-09-27T11_02_03_139Z-debug.log

**Comment by fwh1990** [comment]
应该是我这边的问题。我的binary多了一个分号，我现在修复一下

**Comment by fwh1990** [comment]
等下发布1.0，copy部分需要变更一下，以支持多端同时调试[#2 ]

**Comment by fwh1990** [comment]
已经发布1.0.0，这个问题已经修复了

**Comment by D1N910** [comment]
好的好的

**Comment by D1N910** [comment]
还有问题

**Comment by D1N910** [comment]
Fetching iconfont data...

Creating icons for platform weapp

Cannot find module '/Users/edz/Code/photon-member-fe-webapp/photon-member-fe-webapp/node_modules/mini-program-iconfont-cli/libs/generateWechatComponent'

**Comment by fwh1990** [comment]
你的nodeJs是什么版本？

**Comment by fwh1990** [comment]
以及电脑系统和版本

**Comment by D1N910** [comment]
哥哥，两个建议
（1）修改配置时，可以考虑兼容性，比如你新增了webapp，希望对于原来的wechat也可以兼容下
（2）进行包的修改以后，上传之前，先清理掉node_modules的包内容，重新跑一遍install内容

**Comment by D1N910** [comment]
node 版本v11.14.0
电脑系统 MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

**Comment by D1N910** [comment]
这边是npm安装mini-program-iconfont-cli失败
不过用yarn安装是没问题的，安装的是0.5.1，（推测是因为我用yarn安装的是历史缓存的）

**Comment by fwh1990** [comment]
mini-program-iconfont-cli 现在是0.5.2版本。还有就是taro项目下不需要自己手动安装mini-program-iconfont-cli，会自动安装

**Comment by D1N910** [comment]
之前的问题是安装taro项目不会自动安装成功mini-program-iconfont-cli

**Comment by D1N910** [comment]
现在发现手动npm安装mini-program-iconfont-cli @0.5.2没问题
手动npm 安装mini-program-iconfont-cli @0.5.1报送
npm WARN acorn-jsx@5.0.2 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/d1n910/photon-member-fe-webapp/node_modules/mini-program-iconfont-cli/commands;createQqIcon.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/d1n910/photon-member-fe-webapp/node_modules/mini-program-iconfont-cli/commands;createQqIcon.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/d1n910/.npm/_logs/2019-09-27T13_07_47_680Z-debug.log

**Comment by fwh1990** [comment]
是的，mini-program-iconfont-cli@0.5.1有bug，需要升级到0.5.2。而且我在taro-iconfont-cli中也已经升级mini到0.5.2了

**Comment by fwh1990** [comment]
我想你应该去掉package.json中的mini-program-iconfont-cli，这样taro-iconfont-cli就能指定到正确的mini版本了。

**Comment by D1N910** [comment]
好的，我明天尝试下～谢谢🙏

**Comment by fwh1990** [comment]
> Fetching iconfont data...
> 
> Creating icons for platform weapp
> 
> Cannot find module '/Users/edz/Code/photon-member-fe-webapp/photon-member-fe-webapp/node_modules/mini-program-iconfont-cli/libs/generateWechatComponent'

这个问题是否处于仍未解决状态？

**Comment by D1N910** [comment]
按照你说的，实际上应该是解决了
