### ISSUE TITLE
iconfont/helper.js文件，iconfont路径的疑问

### ISSUE THREAD

**Issue by chuyinweilai** [iconfont-cli/taro-iconfont-cli#42]
```
...
    iconfont: `components\iconfont/${process.env.TARO_ENV}/${process.env.TARO_ENV}`,
...
```
这一行最终生成的代码路径会变成 componentsiconfont/weapp/weapp，我这边小程序会报错
![image](https://user-images.githubusercontent.com/21523040/100406984-23e55780-30a2-11eb-9964-4524596c1f33.png)

修改为：
```
    iconfont: `components/iconfont/${process.env.TARO_ENV}/${process.env.TARO_ENV}`,
```

-- taro info --
  Taro CLI 3.0.17 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 12.16.3 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD

就可以正常运行了，请问下是我的有什么配置出问题了吗？还是插件需要修改下？

**Comment by fwh1990** [comment]
Hello，是因为windows系统路径分割符号不同造成的问题，升级到**3.1.1**后重新生成图标可以解决。

**Comment by chuyinweilai** [comment]
@fwh1990  好的，谢谢！
