### ISSUE TITLE
每次更新图标后需要手动 import Nerv from 'nervjs'

### ISSUE THREAD

**Issue by Chinesee** [iconfont-cli/taro-iconfont-cli#46]
我按照官方文档的说法，加上了 [nervjs 的映射](https://taro-docs.jd.com/taro/docs/next/nerv)，但是在引用图标的时候还是会报 `Nerv is not defined`，需要在 `index.weapp.tsx` 中手动添加 `import Nerv from 'nervjs'` 才能消除，请问是我的用法不对吗？如果是，麻烦大家指教一下～ :smile:

![1111](https://user-images.githubusercontent.com/47730755/103325915-f9affc80-4a88-11eb-9303-75ede314c573.png)

**Comment by fwh1990** [comment]
这个库是基于react编写的

**Comment by Chinesee** [comment]
> 这个库是基于react编写的

那么为什么不能把 react 映射到 nervjs 呢？

**Comment by fwh1990** [comment]
如果nervjs和react完全兼容的话，也是可以这么做的。
