### ISSUE TITLE
生成出来的iconfont是居顶的，是否需要和原本的iconfont一样居中呢？

### ISSUE THREAD

**Issue by D1N910** [iconfont-cli/taro-iconfont-cli#5]

**Comment by fwh1990** [comment]
可以贴一下你的symbol_url吗，我做个测试

**Comment by D1N910** [comment]
//at.alicdn.com/t/font_1007190_61uz5eec4c2.js

留意icon-yamaxun这个

**Comment by fwh1990** [comment]
我试了一下在微信小程序和百度小程序里都是居中的，你是在哪个平台测试的呢？

**Comment by fwh1990** [comment]
![image](https://user-images.githubusercontent.com/11069720/65773798-89bd1300-e16f-11e9-8008-ea3df4c7d46c.png)
我加了背景色上去

**Comment by D1N910** [comment]
我是用微信小程序做的，这个iconfont调成100就是居顶。
也许是我外部定位的问题🤔

**Comment by fwh1990** [comment]
截图里的icon刚好就是100的尺寸。调成其他尺寸也都是居中

**Comment by fwh1990** [comment]
似乎是因为你用了rpx格式

**Comment by D1N910** [comment]
似乎是因为你用了rpx格式
----
是的，我用的rpx

**Comment by fwh1990** [comment]
我发布了新版修复了这个问题，在各个小程序中都能运行。但是H5和RN不支持rpx

**Comment by D1N910** [comment]
好滴，非常感谢🙏

**Comment by fwh1990** [comment]
Hi，H5和RN现在也兼容rpx布局了
