### ISSUE TITLE
H5中显示问题

### ISSUE THREAD

**Issue by 1979024589** [iconfont-cli/taro-iconfont-cli#6]
iconfont的Symbol 
http://at.alicdn.com/t/font_1456754_gi8t7ucksx.js

**Comment by fwh1990** [comment]
Hello，经过测试，Taro在编译h5时，确实遇到了编译失败的问题。我已经修复了这个问题，并发布了新版本，你升级这个库之后，重新执行`npx iconfont-taro`即可
