### ISSUE TITLE
已声明“React”，但从未读取其值。

### ISSUE THREAD

**Issue by idootop** [iconfont-cli/taro-iconfont-cli#65]
<img width="969" alt="图片" src="https://user-images.githubusercontent.com/35302658/136689778-ceb1b7fe-5199-415b-b6d2-f3a2b0361627.png">

或者添加`// @ts-nocheck`，或者移除`React`，谢谢。

当前我们的整个项目除了生成的iconfont文件夹之外都是0 error，0 warn的，所以比较在意这块。

<img width="1001" alt="图片" src="https://user-images.githubusercontent.com/35302658/136689814-1a6862ea-208d-453f-9409-c2b60ca3cdb5.png">

**Comment by fwh1990** [comment]
收到

**Comment by fwh1990** [comment]
我这边不加入React反而会报错，请问你的 tsconfig.json 做了什么特殊处理？

**Comment by idootop** [comment]
> 我这边不加入React反而会报错，请问你的 tsconfig.json 做了什么特殊处理？

也可以在文件首行添加 `// @ts-nocheck`，禁用 vs code 自带的 ts 错误提示

这是我们当前项目的 tsconfig.json

![图片](https://user-images.githubusercontent.com/35302658/136722744-6abcc1ed-ec56-45ae-b9be-13a16576df75.png)

**Comment by 314857493** [comment]
jsx项不使用`react-jsx`，改成`react`就好

**Comment by idootop** [comment]
> jsx项不使用`react-jsx`，改成`react`就好

好的，感谢。
