### ISSUE TITLE
执行npx iconfont-taro的时候提示找不到模块

### ISSUE THREAD

**Issue by StephenOo** [iconfont-cli/taro-iconfont-cli#7]
### 按照步骤（跳过了rn那步）执行了两边，都提示找不到模块
**小程序**
**非ts**
报错如下：
![image](https://user-images.githubusercontent.com/38022683/67003585-da8daf00-f110-11e9-854b-dbbb33c56a79.png)
iconfont/index.js return null

**Comment by fwh1990** [comment]
能提供一下node版本吗，以及使用的操作系统版本。

**Comment by StephenOo** [comment]
> 能提供一下node版本吗，以及使用的操作系统版本。

windows 10.0.18362.418
node 10.16.0

**Comment by fwh1990** [comment]
找到问题了，应该是路径斜杆的问题。中午我修复一下

**Comment by fwh1990** [comment]
@StephenOo  Hello，这个问题已经修复。更新到最新版本即可
