### ISSUE TITLE
快手小程序支持吗？

### ISSUE THREAD

**Issue by GZWZC** [iconfont-cli/taro-iconfont-cli#74]
<img width="643" alt="WechatIMG1209" src="https://user-images.githubusercontent.com/16217142/165454945-6a7efa91-9ae5-4dc4-83c4-f994bb29e80c.png">

**Comment by smackgg** [comment]
@GZWZC 快手小程序可以直接 run weapp，线上稳定运行。 run kwai 问题非常多

**Comment by GZWZC** [comment]
意思是直接执行run weapp。然后在快手里打开微信小程序的dist文件吗

**Comment by smackgg** [comment]
是的 @GZWZC
